version: '3'
services:
  db:
    container_name: warehouse_db
    build:
      context: backend/db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    ports:
      - 3306:3306
  web:
    image: nginx
    volumes:
      - ./web:/etc/nginx/html/warehouse
      - ./web/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8888"
      # - "443:443"
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80