version: '3'
services:
  db:
    container_name: warehouse_db
    build:
      context: backend/db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    ports:
      - 3306:3306